services:
  api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000

  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
